### ISSUE TITLE
license: Repository needs a LICENSE file

### ISSUE THREAD

**Issue by stephen-fox** [andaag/zfs-to-glacier#8]
I somehow missed this before - but the repository is missing a LICENSE file. I took a quick look through the source code and did not find a license...

@andaag, would you mind adding one when you have a chance? Thank you :)

**Comment by andaag** [comment]
Added, sorry about the delay! Had some email filtering issues and github issues on public repos somehow slipped by me!

**Comment by stephen-fox** [comment]
No worries - I just noticed that you added a license file :) Thank you for doing so!
